/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftColumn: typeof import('./src/components/left-column.vue')['default']
    MusicPlayer: typeof import('./src/components/music-player.vue')['default']
  }
}
